[package]
name = "sorting_algos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="merge_sort"
path="./merge_sort.rs"

[dependencies]
rand = "0.8.5"
